### ISSUE TITLE
Crashing if burpbuddy cannot link to the address

### ISSUE THREAD

**Issue by david-hacklabs** [tomsteele/burpbuddy#24]
I noticed that when I start Burp and launch burpbuddy, Burp crashes because burpbuddy tries to link to an LAN IP address that does not correspond to my host anymore.

Burp is trying to preload the settings for burpbuddy located in this config file: /Users/username/Library/Preferences/burp.extensions._burpbuddy.plist

I removed that file, restart the system and now I can launch burpbuddy without problem.

I hope this helps if someone has same issue

**Comment by tomsteele** [comment]
Thanks @david-hacklabs, I've added validation of the IP address to 3.0.0. Coming soon :)

**Comment by david-hacklabs** [comment]
Sounds great. Well done :)
