### ISSUE TITLE
cannot be converted to JSON

### ISSUE THREAD

**Issue by evilpacket** [tomsteele/burpbuddy#25]
While using the 3.0.0 build I get the error
`{"error": "Fri Oct 21 09:15:41 PDT 2016 cannot be converted to JSON"}` after loading in a burp state file and hitting the `/proxyhistory` or `/sitemap` endpoints on the API. 

These routes seem to respond just fine as `[]` with a freshly opened burp / loaded burpbuddy module.

I planned on digging in to figuring out why this happens,  just figured I would log it here until I had a moment to do so.

Burp: 1.7.05

**Comment by tomsteele** [comment]
Oh! I think I found it https://github.com/tomsteele/burpbuddy/blob/6468de38fe6b906d8cad4046193b84e892a3ed2f/src/main/kotlin/burp/BurpToBuddy.kt#L54. I think we just need to convert that to a string. Ideally next week I can complete the documentation and fix this issue. Thanks for the issue :)

**Comment by evilpacket** [comment]
Rad, thanks. <3 burpbuddy.

**Comment by tomsteele** [comment]
Fixed it. I'm just going to overwrite the binary tagged on the beta release for now. 
```
$ curl http://127.0.0.1:8001/sitemap | python -m json.tool | grep expiration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M    0 18.7M    0     0  53.5M      0 --:--:-- --:--:-- --:--:-- 53.5M
                    "expiration": "Mon Sep 05 12:37:20 MDT 2016",
                    "expiration": "Sun Dec 04 11:22:16 MST 2016",
                    "expiration": "Wed Sep 05 12:22:19 MDT 2018",
                    "expiration": "Wed Dec 31 17:00:01 MST 1969",
                    "expiration": "",
                    "expiration": "Wed Dec 31 17:00:01 MST 1969",
                    "expiration": "",
                    "expiration": "Wed Dec 31 17:00:01 MST 1969",
                    "expiration": "Wed Dec 31 17:00:01 MST 1969",
                    "expiration": "Wed Dec 31 17:00:01 MST 1969",
                    "expiration": "Tue Mar 07 11:22:04 MST 2017",
```
