### ISSUE TITLE
listing active scans always returns empty array

### ISSUE THREAD

**Issue by nlf** [tomsteele/burpbuddy#26]
this happens in both 2.4.0 and 3.0.0-BETA, but a simple `GET /scan/active` always returns an empty array, even when there are active scans

**Comment by tomsteele** [comment]
Just to confirm, how are you initiating the scan? There is no way in the burp API to get a list of active scan items. So if you start a scan in BurpSuite, BurpBuddy can not track it. BurpBuddy can only track active scans initiated from the API (it uses an internal data object).

**Comment by nlf** [comment]
well then, disregard :)
