### ISSUE TITLE
Preferred method for receiving Burp's stream of HTTP requests and responses?

### ISSUE THREAD

**Issue by clintgibler** [tomsteele/burpbuddy#28]
The [burpbuddy 2.0 API](https://github.com/tomsteele/burpbuddy/wiki/Version-2-API-(Deprecated)) includes a description of a WebSocket server that allows one to register to receive HTTP requests, responses, and scan issues. However, this API version is deprecated and I don't see similar functionality in the [current API](https://github.com/tomsteele/burpbuddy/wiki/HTTP-API). There's the `GET /proxyhistory` endpoint, but I'm more interested in seeing traffic as it goes through rather than periodically grabbing _all_ of it.

Is there a clean way to get access to the request/response stream in the version 3 API? I'm curious if this functionality was removed for a reason - perhaps it wasn't that useful in practice, was a bit buggy, or is currently being re-vamped and isn't yet released?

Being able to receive all of the requests/responses Burp sees in semi-real time (without having to continuously poll) would be quite useful.

Thanks!

**Comment by tomsteele** [comment]
Hi @clintgibler, I've been meaning to update the docs in the Wiki for sometime. Getting the stream in the version 3 API is now done using the request, response, request/response, and scanner hook URLs. These can be a comma separated list of URLs, and each time an event is fired inside of Burp, the item will be turned into JSON and sent over using a POST to a server you control.

Here is an example of what that looks like in the code:
https://github.com/tomsteele/burpbuddy/blob/master/src/main/kotlin/burp/ScannerListener.kt#L17-L21

The websocket implementation was buggy.

Does that help? I'll try to put some examples on the Wiki soon.

**Comment by clintgibler** [comment]
Hi @tomsteele- thanks for the explanation, I've got it working. 

I've added a brief description of this (and some other misc info I thought people might find helpful) to the HTTP API wiki doc. It could use some more detail, especially on the structure of the hook responses, but let me know if it's a useful start.

**Comment by tomsteele** [comment]
Yeah that looks good, thanks!
