### ISSUE TITLE
Can Request Spider, But How Can I Check Status?

### ISSUE THREAD

**Issue by curtbraz** [tomsteele/burpbuddy#34]
Hello,

First of all, thank you for all of your work on this project!  A great add to Burp Suite Pro.  I have two questions/issues I'm hoping someone can help with.

#1) You can send a target to be spidered.  Typically with manual use I'll run an Active Scan after the spider finishes.  Is there any way from within BurpBuddy's API I can see if the spider queue is 0 to then move on to an active scan?  I don't want to put an arbitrary wait time in my script and I don't want to scan prematurely, missing some of the sitemap.

#2) I need to send a specific Request and have Burp perform that request.  Is my best option to send it to the Repeater using the API or would it be better to do an Active Scan on a specific request?  What I'm trying to do is post credentials to the application so I can do authenticated scanning.  If I could automate a request, I could then store the cookies in the store.  Any advice?

Thank you!

**Comment by 0xdevalias** [comment]
RE 1: To my knowledge/understanding, burp's API doesn't actually expose this functionality at all, so without reverse engineering/hacking support into it, none of these tools/extensions can actually provide that functionality at this stage. (See also: https://github.com/vmware/burp-rest-api/issues/35)

**Comment by tomsteele** [comment]
Yeah this is working as it is designed, burp and burpbuddy are pretty async
