### ISSUE TITLE
Repeater doesn't trigger combo HTTP Request/Response Hook URLs

### ISSUE THREAD

**Issue by iffy** [tomsteele/burpbuddy#36]
Requests made using the Burp Repeater trigger these hooks:

- HTTP Request Hook URLs
- HTTP Response Hook URLs

But do not trigger the combo:

- HTTP Request/Response Hook URLs

Is that expected?

**Comment by tomsteele** [comment]
Yeah, that's expected since I don't think the scanner handles repeater requests, and the req/response hook is built using a fake scanner.
